-- Σ SIGMA RADAR Fit V4.1.0 — sono diário
create table if not exists public.sleep_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  log_date date not null,
  hours numeric(4,2) not null check (hours > 0 and hours <= 24),
  target_hours numeric(4,2),
  source text default 'user',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(user_id, log_date)
);
alter table public.sleep_logs enable row level security;
drop policy if exists sleep_logs_own on public.sleep_logs;
create policy sleep_logs_own on public.sleep_logs for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
