-- SIGMA RADAR Fit V2.1.0
-- Memória do Σ Coach, outras atividades e planejamento multi-dia

alter table public.profiles add column if not exists other_activities_text text;
alter table public.profiles add column if not exists other_activities jsonb not null default '[]'::jsonb;

alter table public.workout_plans add column if not exists activities jsonb not null default '[]'::jsonb;

create table if not exists public.activity_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  log_date date not null,
  activity_key text not null,
  activity_name text not null,
  duration_min numeric,
  completed boolean not null default false,
  notes text,
  source text not null default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, log_date, activity_key)
);

alter table public.activity_logs enable row level security;
drop policy if exists "activity_logs_select_own" on public.activity_logs;
drop policy if exists "activity_logs_insert_own" on public.activity_logs;
drop policy if exists "activity_logs_update_own" on public.activity_logs;
drop policy if exists "activity_logs_delete_own" on public.activity_logs;
create policy "activity_logs_select_own" on public.activity_logs for select using (auth.uid() = user_id);
create policy "activity_logs_insert_own" on public.activity_logs for insert with check (auth.uid() = user_id);
create policy "activity_logs_update_own" on public.activity_logs for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "activity_logs_delete_own" on public.activity_logs for delete using (auth.uid() = user_id);

create table if not exists public.coach_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user','assistant')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists coach_messages_user_created_idx on public.coach_messages(user_id, created_at desc);
alter table public.coach_messages enable row level security;
drop policy if exists "coach_messages_select_own" on public.coach_messages;
drop policy if exists "coach_messages_insert_own" on public.coach_messages;
drop policy if exists "coach_messages_delete_own" on public.coach_messages;
create policy "coach_messages_select_own" on public.coach_messages for select using (auth.uid() = user_id);
create policy "coach_messages_insert_own" on public.coach_messages for insert with check (auth.uid() = user_id);
create policy "coach_messages_delete_own" on public.coach_messages for delete using (auth.uid() = user_id);
