(function(){
const $=id=>document.getElementById(id),TZ='America/Sao_Paulo';
const color=r=>{const n=Number(r?.roll??r?.number??r?.value);return n===0||r?.color==='white'||r?.color===0?'white':n>=1&&n<=7?'red':'black'};
const roundDate=r=>new Date(r?.createdAt||r?.created_at||r?.timestamp||0);
const parts=d=>{if(!(d instanceof Date)||isNaN(d))return null;const p=new Intl.DateTimeFormat('en-US',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d);return Object.fromEntries(p.map(x=>[x.type,x.value]))};
const dateKey=d=>{const p=parts(d);return p?`${p.year}-${p.month}-${p.day}`:''};
const fmtTime=v=>{const d=v instanceof Date?v:new Date(v);return isNaN(d)?'—':new Intl.DateTimeFormat('pt-BR',{timeZone:TZ,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(d)};
const pct=n=>`${(Number(n||0)*100).toFixed(1).replace('.',',')}%`;
function render(){const rounds=window.SIGMA_LIVE_ENGINE?.rounds||[];if(!rounds.length)return;const now=Date.now(),today=dateKey(new Date()),whites=rounds.filter(r=>color(r)==='white'),w24=whites.filter(r=>now-roundDate(r).getTime()<=86400000);$('rsWhites24').textContent=w24.length;$('rsWhites24Sub').textContent=`${whites.length} nas ${rounds.length} carregadas`;let gaps=[];for(let i=1;i<whites.length;i++){const a=rounds.indexOf(whites[i-1]),b=rounds.indexOf(whites[i]);if(a>=0&&b>a)gaps.push(b-a)};$('rsAvgGap').textContent=gaps.length?(gaps.reduce((a,b)=>a+b,0)/gaps.length).toFixed(1).replace('.',','):'—';$('rsMaxGap').textContent=gaps.length?Math.max(...gaps):'—';const recent=rounds.slice(-60),rw=recent.filter(r=>color(r)==='white').length,expected=60*(whites.length/rounds.length);let regime=rw>=expected*1.35?'PIPOCANDO':rw<=expected*.65?'RECUPERAÇÃO':'NORMAL';$('rsRegime').textContent=regime;$('rsRegimeSub').textContent=`${rw} brancos nas últimas 60 rodadas`;
const mins=Array(60).fill(0),hrsToday=Array(24).fill(0);whites.forEach(r=>{const d=roundDate(r),p=parts(d);if(!p)return;mins[+p.minute]++;if(dateKey(d)===today)hrsToday[+p.hour]++;});const maxM=Math.max(...mins,1),sortedM=[...mins].sort((a,b)=>a-b),q=sortedM[Math.floor(sortedM.length*.75)];$('rsMinutes').innerHTML=mins.map((v,i)=>`<div class="paying-minute ${v===maxM?'strong':v>=q?'hot':''}" title="${v} brancos nas 3000 rodadas"><span>${String(i).padStart(2,'0')}</span></div>`).join('');const top=hrsToday.map((v,h)=>({h,v})).filter(x=>x.v>0).sort((a,b)=>b.v-a.v||a.h-b.h).slice(0,6),maxH=Math.max(...top.map(x=>x.v),1);$('rsHours').innerHTML=top.length?top.map(x=>`<div class="radar-rank"><strong>${String(x.h).padStart(2,'0')}:00</strong><i><b style="width:${x.v/maxH*100}%"></b></i><span>${x.v} ⚪</span></div>`).join(''):'<div class="radar-hour-empty">Ainda não há brancos registrados hoje.</div>';const lastWhite=whites.at(-1),lastIdx=lastWhite?rounds.indexOf(lastWhite):-1,delay=lastIdx>=0?rounds.length-1-lastIdx:null;$('rsNow').innerHTML=`<strong>Regime:</strong> ${regime}<br><strong>Atraso atual:</strong> ${delay??'—'} rodadas<br><strong>Últimas 60:</strong> ${rw} brancos<br><strong>Taxa base:</strong> ${(whites.length/rounds.length*100).toFixed(1).replace('.',',')}%`;$('rsProjection').textContent=regime==='PIPOCANDO'?'Concentração recente acima do comportamento médio. O Radar identifica maior atividade, sem transformar isso em garantia de novo branco.':regime==='RECUPERAÇÃO'?'Concentração recente abaixo do comportamento médio. O Radar recomenda leitura mais seletiva enquanto a distribuição se recompõe.':'Distribuição recente próxima do comportamento médio das rodadas carregadas.';}
function renderHourRadar(payload){const root=$('rsHourRadar'),note=$('rsHourRadarNote');if(!root)return;const data=payload?.hourRadar||payload||{},points=Array.isArray(data.points)?data.points:[];if(!points.length){root.innerHTML=`<div class="radar-hour-empty">${data.message||'Nenhum ponto disponível nesta hora.'}</div>`;if(note)note.textContent='O Radar recalcula a leitura quando novas rodadas chegam.';return;}root.innerHTML=points.map((p,i)=>{const status=p.status==='CONTEXTO_VALIDADO'?'CONTEXTO FORTE':p.status==='CONTEXTO_EM_OBSERVACAO'?'CONTEXTO':'RADAR',cls=p.status==='CONTEXTO_VALIDADO'?'is-strong':p.status==='CONTEXTO_EM_OBSERVACAO'?'is-context':'',detail=p.labels?.length?p.labels.join(' • '):`Histórico do minuto ${String(p.minute).padStart(2,'0')}`;return `<article class="radar-hour-point ${cls}"><span class="radar-hour-rank">${String(i+1).padStart(2,'0')}</span><strong>${fmtTime(p.targetAt)}</strong><em>${status}</em><small>${detail}</small><b>${pct(p.estimatedRate)}</b></article>`}).join('');if(note)note.textContent=`Regime do motor: ${data.regime||'—'} • referência-base ${pct(data.baseline)} • pontos recalculados em tempo real.`;}
async function syncWhiteRadar(){try{const base=window.SIGMA_LIVE_SERVER_URL||'https://sigma-live-server.onrender.com',res=await fetch(`${base}/api/sigma-white/state?t=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error('white state');renderHourRadar(await res.json());}catch(e){console.warn('[SIGMA RADAR STATS]',e);renderHourRadar({points:[],message:'Motor BRANCO temporariamente indisponível.'});}}
window.addEventListener('sigma:live-round',()=>{render();syncWhiteRadar()});window.addEventListener('sigma:memory-reconciled',()=>{render();syncWhiteRadar()});window.addEventListener('sigma:catalog-rendered',render);setTimeout(()=>{render();syncWhiteRadar()},1200);setInterval(syncWhiteRadar,15000);})();
