(function(){
const $=id=>document.getElementById(id); const color=r=>{const n=Number(r?.roll??r?.number??r?.value);return n===0||r?.color==='white'||r?.color===0?'white':n>=1&&n<=7?'red':'black'};
function render(){const rounds=window.SIGMA_LIVE_ENGINE?.rounds||[];if(!rounds.length)return;const now=Date.now(), whites=rounds.filter(r=>color(r)==='white');const w24=whites.filter(r=>now-new Date(r.createdAt||r.created_at).getTime()<=86400000);$('rsWhites24').textContent=w24.length;$('rsWhites24Sub').textContent=`${whites.length} nas ${rounds.length} carregadas`;
let gaps=[];for(let i=1;i<whites.length;i++){const a=rounds.indexOf(whites[i-1]),b=rounds.indexOf(whites[i]);if(a>=0&&b>a)gaps.push(b-a)};$('rsAvgGap').textContent=gaps.length?(gaps.reduce((a,b)=>a+b,0)/gaps.length).toFixed(1).replace('.',','):'—';$('rsMaxGap').textContent=gaps.length?Math.max(...gaps):'—';
const recent=rounds.slice(-60),rw=recent.filter(r=>color(r)==='white').length, expected=60*(whites.length/rounds.length);let regime=rw>=expected*1.35?'PIPOCANDO':rw<=expected*.65?'RECUPERAÇÃO':'NORMAL';$('rsRegime').textContent=regime;$('rsRegimeSub').textContent=`${rw} brancos nas últimas 60 rodadas`;
const mins=Array(60).fill(0),hrs=Array(24).fill(0);whites.forEach(r=>{const d=new Date(r.createdAt||r.created_at);if(!isNaN(d)){const parts=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d);const o=Object.fromEntries(parts.map(x=>[x.type,x.value]));mins[+o.minute]++;hrs[+o.hour]++;}});const maxM=Math.max(...mins,1),sortedM=[...mins].sort((a,b)=>a-b),q=sortedM[Math.floor(sortedM.length*.75)];$('rsMinutes').innerHTML=mins.map((v,i)=>`<div class="paying-minute ${v===maxM?'strong':v>=q?'hot':''}" title="${v} brancos"><span>${String(i).padStart(2,'0')}</span></div>`).join('');
const top=hrs.map((v,h)=>({h,v})).sort((a,b)=>b.v-a.v).slice(0,6),maxH=Math.max(...top.map(x=>x.v),1);$('rsHours').innerHTML=top.map((x,i)=>`<div class="radar-rank"><strong>${String(x.h).padStart(2,'0')}:00</strong><i><b style="width:${x.v/maxH*100}%"></b></i><span>${x.v} ⚪</span></div>`).join('');
const lastWhite=whites.at(-1),lastIdx=lastWhite?rounds.indexOf(lastWhite):-1,delay=lastIdx>=0?rounds.length-1-lastIdx:null;$('rsNow').innerHTML=`<strong>Regime:</strong> ${regime}<br><strong>Atraso atual:</strong> ${delay??'—'} rodadas<br><strong>Últimas 60:</strong> ${rw} brancos<br><strong>Taxa base:</strong> ${(whites.length/rounds.length*100).toFixed(1).replace('.',',')}%`;$('rsProjection').textContent=regime==='PIPOCANDO'?'Concentração recente acima do comportamento médio. O Radar identifica maior atividade, sem transformar isso em garantia de novo branco.':regime==='RECUPERAÇÃO'?'Concentração recente abaixo do comportamento médio. O Radar recomenda leitura mais seletiva enquanto a distribuição se recompõe.':'Distribuição recente próxima do comportamento médio das rodadas carregadas.';}
window.addEventListener('sigma:live-round',render);window.addEventListener('sigma:memory-reconciled',render);window.addEventListener('sigma:catalog-rendered',render);setTimeout(render,1200);
})();
