let analystToken=sessionStorage.getItem('sigmaAnalystToken')||'';
function pad(v){return String(v).padStart(2,'0')}
function shiftMinute(time,delta){const [h,m]=time.split(':').map(Number);const d=new Date(2000,0,1,h,m+delta);return `${pad(d.getHours())}:${pad(d.getMinutes())}`}
function escapeHtml(text){return String(text??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function todayBrazil(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date())}
function showToast(message,type='ok'){const el=document.getElementById('toast');el.textContent=message;el.className=`toast ${type} show`;setTimeout(()=>el.className='toast',2600)}
function authHeaders(){return {'Content-Type':'application/json','Authorization':`Bearer ${analystToken}`}}
function signalType(signal){return String(signal?.meta?.tipo||'WHITE').toUpperCase()}
async function login(){const password=document.getElementById('password').value;const response=await fetch('/api/analista-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!response.ok){document.getElementById('loginError').classList.add('show');return}const data=await response.json();analystToken=data.token;sessionStorage.setItem('sigmaAnalystToken',analystToken);openPanel()}
function logout(){sessionStorage.removeItem('sigmaAnalystToken');analystToken='';location.reload()}
function openPanel(){document.getElementById('loginCard').style.display='none';document.getElementById('panel').classList.add('show');const today=todayBrazil();document.getElementById('whiteDate').value=today;document.getElementById('colorDate').value=today;loadActive()}
async function verifySession(){if(!analystToken)return;const response=await fetch('/api/analista-sinais',{headers:authHeaders()});if(response.ok)openPanel();else logout()}
function whiteCard(signal){const meta=signal.meta||{};return `<article class="signal white-signal"><div class="signal-top"><strong class="signal-time">${escapeHtml(signal.horario)}</strong><span class="status">WHITE ATIVO</span></div><div class="window">${shiftMinute(signal.horario,-1)} • ${escapeHtml(signal.horario)} • ${shiftMinute(signal.horario,1)}</div><div class="note">${escapeHtml(meta.texto||'Sem observação')} · ${'★'.repeat(meta.confianca||5)}</div><div class="result-row"><select id="resultMinute-${signal.id}"><option value="${shiftMinute(signal.horario,-1)}">Branco em ${shiftMinute(signal.horario,-1)}</option><option value="${signal.horario}" selected>Branco em ${signal.horario}</option><option value="${shiftMinute(signal.horario,1)}">Branco em ${shiftMinute(signal.horario,1)}</option></select><button class="btn btn-win" onclick="finishWhite(${signal.id},'pago')">PAGO</button><button class="btn btn-loss" onclick="finishWhite(${signal.id},'falhou')">FALHOU</button><button class="btn btn-delete" onclick="deleteSignal(${signal.id})">EXCLUIR</button></div></article>`}
function colorCard(signal){const meta=signal.meta||{};const color=meta.cor==='BLACK'?'PRETO':'VERMELHO';const cls=meta.cor==='BLACK'?'black':'red';return `<article class="signal color-signal"><div class="signal-top"><strong class="signal-time">${escapeHtml(signal.horario)}</strong><span class="status">COLOR ATIVO</span></div><div class="entry-line"><i class="entry-dot ${cls}"></i> Entrada no ${color} • proteção até G1</div><div class="note">${escapeHtml(meta.texto||'Sem observação')} · ${'★'.repeat(meta.confianca||5)}</div><div class="result-row"><button class="btn btn-win" onclick="finishColor(${signal.id},'DIRETA')">WIN DIRETA</button><button class="btn btn-g1" onclick="finishColor(${signal.id},'G1')">WIN G1</button><button class="btn btn-loss" onclick="finishColor(${signal.id},'LOSS')">LOSS</button><button class="btn btn-delete" onclick="deleteSignal(${signal.id})">EXCLUIR</button></div></article>`}
async function loadActive(){const response=await fetch('/api/analista-sinais',{headers:authHeaders(),cache:'no-store'});if(response.status===401)return logout();const data=await response.json();const list=data.active||[];const whites=list.filter(s=>signalType(s)==='WHITE');const colors=list.filter(s=>signalType(s)==='COLOR');document.getElementById('activeCounter').textContent=`${list.length} ativo${list.length===1?'':'s'}`;document.getElementById('activeWhiteList').innerHTML=whites.length?whites.map(whiteCard).join(''):'<div class="empty">Nenhum WHITE ativo.</div>';document.getElementById('activeColorList').innerHTML=colors.length?colors.map(colorCard).join(''):'<div class="empty">Nenhum COLOR ativo.</div>'}
async function publish(payload,buttonId,clearId){const button=document.getElementById(buttonId);button.disabled=true;const response=await fetch('/api/analista-sinais',{method:'POST',headers:authHeaders(),body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));button.disabled=false;if(!response.ok)return showToast(data.error||'Não foi possível publicar.','bad');document.getElementById(clearId).value='';if(data.telegram?.ok===false)showToast('Publicado no site, mas o Telegram falhou.','warn');else if(data.telegram?.configured===false)showToast('Publicado no site. Configure o Telegram na Vercel.','warn');else showToast('Publicado no site e no Telegram.');loadActive()}
function publishWhite(){const payload={tipo:'WHITE',data_operacao:document.getElementById('whiteDate').value,horario:document.getElementById('whiteTime').value,observacao:document.getElementById('whiteNote').value.trim(),confianca:Number(document.getElementById('whiteConfidence').value),margem:1};if(!payload.data_operacao||!payload.horario)return showToast('Informe data e horário do WHITE.','bad');publish(payload,'publishWhiteBtn','whiteNote')}
function publishColor(){const payload={tipo:'COLOR',data_operacao:document.getElementById('colorDate').value,horario:document.getElementById('colorTime').value,observacao:document.getElementById('colorNote').value.trim(),confianca:Number(document.getElementById('colorConfidence').value),cor:document.querySelector('input[name="entryColor"]:checked')?.value||'RED',gale:Number(document.getElementById('colorGale').value)||1};if(!payload.data_operacao||!payload.horario)return showToast('Informe data e horário do COLOR.','bad');publish(payload,'publishColorBtn','colorNote')}
async function finishWhite(id,status){const minuto=status==='pago'?document.getElementById(`resultMinute-${id}`).value:null;await finishSignal({id,status,minuto_resultado:minuto,resultado:status==='pago'?'PAGO':'FALHOU'})}
async function finishColor(id,resultado){await finishSignal({id,status:resultado==='LOSS'?'falhou':'pago',resultado})}
async function finishSignal(payload){const response=await fetch('/api/analista-sinais',{method:'PATCH',headers:authHeaders(),body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)return showToast(data.error||'Erro ao encerrar.','bad');showToast(`Sinal encerrado: ${payload.resultado}.`);loadActive()}
async function deleteSignal(id){if(!confirm('Excluir este sinal definitivamente?'))return;const response=await fetch(`/api/analista-sinais?id=${id}`,{method:'DELETE',headers:authHeaders()});if(!response.ok)return showToast('Erro ao excluir.','bad');showToast('Sinal excluído.');loadActive()}
verifySession();setInterval(()=>{if(analystToken)loadActive()},5000);
