const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let sb=null, session=null;
const S={mode:'signup',p:{},q:0,days:[],foods:[],customFoods:[],filter:'all',selected:new Map(),plan:null,ex:new Set(),mealsDone:new Set(),water:0,history:[],currentDate:'',dayStatus:'in_progress',steps:0,bodyHistory:[],loadHistory:[],editingMealKey:null};
const DAYS=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'];
const POSES=['coach-guiding.png','coach-checkin.png','coach-checkin.png','coach-checkin.png','coach-guiding.png','coach-guiding.png','coach-checkin.png','coach-checkin.png','coach-analysis.png','coach-analysis.png','coach-thinking.png','coach-thinking.png','coach-hydration.png','coach-checkin.png','coach-celebrate.png'];
const Q=[
 ['sex','Para começar: qual é o seu sexo?','opts',[['masculino','Masculino'],['feminino','Feminino'],['outro','Prefiro não informar']]],
 ['age','Qual é a sua idade?','number'],['height_cm','E sua altura em centímetros?','number'],['current_weight_kg','Qual é seu peso atual?','number'],
 ['goal_text','Agora me conta com suas palavras: <b>o que você quer alcançar?</b><br><br>Pode escrever naturalmente. Eu vou usar isso como contexto do plano.','goal'],
 ['training_days','Quais dias você pretende treinar? Pode escolher mais de um.','days'],
 ['minutes_per_session','Quanto tempo você consegue reservar por treino?','opts',[['30','Até 30 min'],['45','45 min'],['60','60 min'],['75','75 min'],['90','90 min ou mais']]],
 ['experience','Como está sua experiência com musculação hoje?','opts',[['iniciante','Estou começando'],['intermediario','Já treino há algum tempo'],['avancado','Treino há anos']]],
 ['medications_text','Você usa algum medicamento que possa influenciar peso, apetite, energia ou treino?<br><br>Pode responder do seu jeito. Eu uso isso como contexto, não para alterar dose ou tratamento.','meds'],
 ['supplements_text','E suplementos? Usa algum atualmente?','supps'],['target_weight_kg','Você tem um peso-alvo em mente?','number'],
 ['meals_per_day','Quantas refeições funcionam melhor na sua rotina?','opts',[['3','3 refeições'],['4','4 refeições'],['5','5 refeições'],['6','6 refeições']]],
 ['current_water_l','Quanto de água costuma beber hoje?','opts',[['1','Até 1 L'],['1.5','1,5 L'],['2','2 L'],['3','3 L ou mais'],['0','Não sei']]],
 ['steps_goal','Você costuma acompanhar seus passos por dia? Se souber, informe uma média ou meta. Se não souber, pode escolher “Não sei”.','opts',[['0','Não sei / não acompanho'],['5000','Cerca de 5.000'],['7500','Cerca de 7.500'],['10000','Cerca de 10.000'],['12000','12.000 ou mais']]],
 ['sleep_hours','Quantas horas você costuma dormir?','opts',[['5','5h ou menos'],['6','6h'],['7','7h'],['8','8h ou mais']]],
 ['finish',p=>`Perfeito. Seu objetivo ficou registrado como <b>“${p.goal_text||'—'}”</b>.<br><br>Agora eu já tenho um bom ponto de partida. Vou montar seu primeiro plano.`,'opts',[['go','MONTAR MEU PLANO →']]]
];
const EXBASE=[['Supino reto','4 × 8–10'],['Puxada alta','4 × 8–12'],['Remada baixa','3 × 10–12'],['Desenvolvimento','3 × 8–10'],['Elevação lateral','3 × 12–15'],['Tríceps na polia','3 × 10–12']];

function localDate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function dateAdd(date,days){const [y,m,d]=date.split('-').map(Number),x=new Date(y,m-1,d);x.setDate(x.getDate()+days);return localDate(x)}
function formatDate(date){const [y,m,d]=date.split('-').map(Number);return new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'short',year:'numeric'}).format(new Date(y,m-1,d))}
function configured(){return !!(window.SIGMA_CONFIG?.SUPABASE_URL&&window.SIGMA_CONFIG?.SUPABASE_ANON_KEY)}
function initSupabase(){if(configured())sb=window.supabase.createClient(SIGMA_CONFIG.SUPABASE_URL,SIGMA_CONFIG.SUPABASE_ANON_KEY)}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo(0,0)}
function auth(m){show('auth');setMode(m)}
function setMode(m){S.mode=m;$('#signTab').classList.toggle('active',m==='signup');$('#loginTab').classList.toggle('active',m==='login');$('#name').style.display=m==='signup'?'block':'none';$('#authTitle').textContent=m==='signup'?'Crie sua conta':'Entre no Sigma';$('#authBtn').textContent=m==='signup'?'CRIAR CONTA →':'ENTRAR →';$('#authMsg').textContent=''}

async function submitAuth(){
 if(!configured())return $('#authMsg').textContent='Supabase ainda não configurado.';
 const n=$('#name').value.trim(),e=$('#email').value.trim(),p=$('#pass').value;
 if(!e||p.length<6||(S.mode==='signup'&&!n))return $('#authMsg').textContent='Preencha os dados corretamente. A senha precisa ter ao menos 6 caracteres.';
 $('#authBtn').disabled=true;
 try{
  if(S.mode==='signup'){
   const {data,error}=await sb.auth.signUp({email:e,password:p,options:{data:{name:n}}});if(error)throw error;
   if(!data.session){$('#authMsg').textContent='Conta criada. Confirme seu e-mail e depois entre.';return}
   session=data.session;S.p={id:data.user.id,name:n,email:e};await upsertProfile({id:data.user.id,name:n});startInterview();
  }else{
   const {data,error}=await sb.auth.signInWithPassword({email:e,password:p});if(error)throw error;session=data.session;await loadProfileAndEnter(data.user);
  }
 }catch(err){$('#authMsg').textContent=err.message||'Não foi possível continuar.'}finally{$('#authBtn').disabled=false}
}
async function upsertProfile(obj){const {error}=await sb.from('profiles').upsert(obj,{onConflict:'id'});if(error)throw error}
async function loadProfileAndEnter(user){const {data,error}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)throw error;S.p=data||{id:user.id,name:user.user_metadata?.name||'Atleta'};if(!S.p.onboarding_complete)startInterview();else{S.currentDate=localDate();await loadAppData();show('app');renderApp()}}

function startInterview(){show('interview');S.q=0;S.days=[];renderQ()}
function renderQ(){const q=Q[S.q],txt=typeof q[1]==='function'?q[1](S.p):q[1];$('#bar').style.width=((S.q+1)/Q.length*100)+'%';$('#count').textContent=(S.q+1)+'/'+Q.length;$('#interviewCoach').src='assets/coach/'+POSES[S.q];$('#chat').innerHTML=`<div class="bubble coach singleOnly">${txt}</div>`;renderA(q)}
function renderA(q){const t=q[2],a=$('#answers');if(t==='opts')a.innerHTML=`<div class="quick">${q[3].map(o=>`<button onclick="ans('${o[0]}','${o[1]}')">${o[1]}</button>`).join('')}</div>`;else if(t==='days')a.innerHTML=`<div class="days">${DAYS.map(d=>`<button onclick="toggleDay(this,'${d}')">${d.substring(0,3)}</button>`).join('')}</div><button style="margin-top:10px" onclick="confirmDays()">CONFIRMAR →</button>`;else{let sug=t==='goal'?['Quero emagrecer sem perder massa','Quero perder gordura e ganhar massa','Quero ganhar massa muscular']:t==='meds'?['Não uso medicamentos','Uso Mounjaro / tirzepatida','Uso semaglutida']:t==='supps'?['Não uso suplementos','Whey + creatina','Creatina']:[];a.innerHTML=`<div class="textAnswer"><input id="txt" placeholder="Escreva aqui..." onkeydown="if(event.key==='Enter')sendA()"><button onclick="sendA()">ENVIAR →</button></div>${sug.length?`<div class="quick suggestions">${sug.map(s=>`<button onclick="fill('${s.replace(/'/g,'')}')">${s}</button>`).join('')}</div>`:''}`;setTimeout(()=>$('#txt')?.focus(),20)}}
function fill(t){$('#txt').value=t;$('#txt').focus()}function sendA(){const v=$('#txt').value.trim();if(v)ans(v,v)}
function toggleDay(b,d){b.classList.toggle('selected');S.days.includes(d)?S.days=S.days.filter(x=>x!==d):S.days.push(d)}
function confirmDays(){if(!S.days.length)return toast('Escolha pelo menos um dia.');ans(S.days,S.days.join(', '))}
function ans(v,l){const q=Q[S.q];S.p[q[0]]=v;$('#chat').classList.add('fadeInterview');$('#answers').classList.add('fadeInterview');setTimeout(()=>{if(q[0]==='finish')return build();S.q++;$('#chat').classList.remove('fadeInterview');$('#answers').classList.remove('fadeInterview');renderQ()},220)}

function signals(){const g=(S.p.goal_text||'').toLowerCase(),m=(S.p.medications_text||'').toLowerCase();return{loss:/perd|emagrec|gordura|secar|defin/.test(g),gain:/ganhar massa|hipertrof|massa muscular/.test(g),glp1:/mounjaro|tirzep|semaglut|wegovy|ozempic/.test(m)}}
function makePlan(){
 let w=parseFloat(String(S.p.current_weight_kg).replace(',','.'))||90,h=+S.p.height_cm||175,a=+S.p.age||30,sexAdj=S.p.sex==='feminino'?-161:5,bmr=10*w+6.25*h-5*a+sexAdj,days=(S.p.training_days||[]).length||3,activity=days>=5?1.52:days>=3?1.43:1.34,tdee=bmr*activity,sg=signals(),cal=tdee;
 if(sg.loss&&sg.gain)cal-=650;else if(sg.loss)cal-=700;else if(sg.gain)cal+=250;cal=Math.round(cal/50)*50;if(sg.loss&&sg.glp1)cal=Math.min(cal,w>=90?2050:1900);cal=Math.max(cal,S.p.sex==='feminino'?1400:1600);
 const prot=Math.round(w*2),fat=Math.round(w*.65),carb=Math.max(80,Math.round((cal-prot*4-fat*9)/4)),water=Math.max(2.2,w*.035),count=+S.p.meals_per_day||4;
 const names=count===3?['Café da manhã','Almoço','Jantar']:count===4?['Café da manhã','Almoço','Lanche','Jantar']:count===5?['Café da manhã','Lanche da manhã','Almoço','Lanche / pré-treino','Jantar']:['Café da manhã','Lanche da manhã','Almoço','Lanche da tarde','Jantar','Ceia'];
 const times=count===3?['08:00','13:00','20:00']:count===4?['08:00','12:30','16:30','20:30']:count===5?['08:00','11:00','14:00','17:30','20:30']:['07:30','10:30','13:00','16:00','19:00','21:30'];
 const mealFoods=[['Ovos','Pão integral','Banana'],['Iogurte proteico','Aveia','Morango'],['Peito de frango grelhado','Arroz branco cozido','Feijão carioca','Salada'],['Whey protein concentrado','Banana prata'],['Tilápia grelhada','Batata inglesa cozida','Brócolis'],['Queijo cottage','Maçã gala']];
 const meals=names.map((n,i)=>({key:'meal_'+i,name:n,time:times[i],target:Math.round(cal/count),foods:mealFoods[i]||mealFoods.at(-1)}));
 const exercises=EXBASE.map((e,i)=>({key:'ex_'+i,name:e[0],scheme:e[1]}));
 const reason=sg.loss?`Déficit inicial moderado para perda de gordura, com proteína alta para preservar massa magra${sg.glp1?'. A medicação informada foi usada como contexto de apetite e tolerância, nunca como orientação de dose':''}.`:'Meta inicial calculada a partir do gasto estimado e objetivo informado.';
 return{cal,prot,fat,carb,water,count,meals,exercises,reason}
}
async function build(){show('building');S.plan=makePlan();$$('#checks span').forEach((x,i)=>setTimeout(()=>{x.textContent='✓ '+x.textContent.slice(2);x.style.color='#1f7a5a'},300+i*270));setTimeout(()=>$('#buildText').textContent='Criando refeições, treino e calibrando o Σ Score...',900);try{const clean={id:session.user.id,name:S.p.name,sex:S.p.sex||null,age:S.p.age?Number(S.p.age):null,height_cm:S.p.height_cm?Number(String(S.p.height_cm).replace(',','.')):null,current_weight_kg:S.p.current_weight_kg?Number(String(S.p.current_weight_kg).replace(',','.')):null,target_weight_kg:S.p.target_weight_kg?Number(String(S.p.target_weight_kg).replace(',','.')):null,goal_text:S.p.goal_text||null,training_days:Array.isArray(S.p.training_days)?S.p.training_days:[],minutes_per_session:S.p.minutes_per_session?Number(S.p.minutes_per_session):null,experience:S.p.experience||null,medications_text:S.p.medications_text||null,supplements_text:S.p.supplements_text||null,meals_per_day:S.p.meals_per_day?Number(S.p.meals_per_day):4,current_water_l:S.p.current_water_l?Number(S.p.current_water_l):0,sleep_hours:S.p.sleep_hours?Number(S.p.sleep_hours):null,steps_goal:S.p.steps_goal?Number(S.p.steps_goal):null,onboarding_complete:true,calorie_target:S.plan.cal,protein_target:S.plan.prot,carbs_target:S.plan.carb,fat_target:S.plan.fat,water_target_l:S.plan.water,score:70};await upsertProfile(clean);S.p={...S.p,...clean};S.currentDate=localDate();setTimeout(async()=>{await loadAppData();show('app');renderApp()},800)}catch(err){console.error(err);$('#buildText').innerHTML='Não consegui salvar o plano no banco.<br><b>'+String(err.message||err)+'</b>'}}

async function loadFoods(){try{const base=await (await fetch('assets/foods.json')).json();S.customFoods=[];if(sb&&session){const {data}=await sb.from('custom_foods').select('*').eq('user_id',session.user.id).order('created_at',{ascending:false});S.customFoods=data||[]}const custom=S.customFoods.map(x=>({name:x.name,cat:x.category,portion:x.portion_label,kcal:+x.kcal,p:+x.protein_g,c:+x.carbs_g,f:+x.fat_g,origin:'Meu alimento',approx:false,_customId:x.id}));S.foods=[...custom,...base]}catch(e){console.error(e);S.foods=[]}}
async function loadAppData(){S.plan=makePlan();S.plan.cal=S.p.calorie_target||S.plan.cal;S.plan.prot=S.p.protein_target||S.plan.prot;S.plan.carb=S.p.carbs_target||S.plan.carb;S.plan.fat=S.p.fat_target||S.plan.fat;S.plan.water=S.p.water_target_l||S.plan.water;await loadFoods();await loadDayData();const {data:h}=await sb.from('daily_logs').select('*').eq('user_id',session.user.id).order('log_date',{ascending:false}).limit(14);S.history=h||[];await loadEvolutionData()}
async function loadDayData(){
 S.ex=new Set();S.mealsDone=new Set();S.water=0;S.steps=0;S.dayStatus='in_progress';const date=S.currentDate||localDate();
 const [{data:ex},{data:ml},{data:dl},{data:bl}]=await Promise.all([sb.from('exercise_logs').select('*').eq('user_id',session.user.id).eq('log_date',date),sb.from('meal_logs').select('*').eq('user_id',session.user.id).eq('log_date',date),sb.from('daily_logs').select('*').eq('user_id',session.user.id).eq('log_date',date).maybeSingle(),sb.from('body_logs').select('*').eq('user_id',session.user.id).eq('log_date',date).maybeSingle()]);
 S.ex=new Set((ex||[]).filter(x=>x.completed).map(x=>x.exercise_key));S.mealsDone=new Set((ml||[]).filter(x=>x.completed).map(x=>x.meal_key));S.water=+dl?.water_l||0;S.steps=+bl?.steps||0;S.dayStatus=dl?.status||'in_progress';
 for(const x of (ml||[])){if(x.deleted)continue;if(x.foods&&Array.isArray(x.foods)){const meal={key:x.meal_key,name:x.meal_name,time:(x.meal_time||'').slice(0,5),target:Math.round(+x.kcal||0),protein:+x.protein_g||0,carbs:+x.carbs_g||0,fat:+x.fat_g||0,foodItems:normalizeFoodItems(x.foods),foods:normalizeFoodItems(x.foods).map(foodLabel)};const ix=S.plan.meals.findIndex(m=>m.key===x.meal_key);if(ix>=0)S.plan.meals[ix]={...S.plan.meals[ix],...meal};else S.plan.meals.push(meal)}}
 S.plan.meals.forEach(enrichMeal);
}
function renderApp(){const first=(S.p.name||'Atleta').split(' ')[0];$('#hello').textContent='Olá, '+first+'.';$('#cal').textContent=S.plan.cal.toLocaleString('pt-BR');$('#prot').textContent=S.plan.prot+' g';$('#carb').textContent=S.plan.carb+' g';$('#fat').textContent=S.plan.fat+' g';$('#calorieReason').textContent=S.plan.reason;$('#waterGoal').textContent='meta: '+S.plan.water.toFixed(1).replace('.',',')+' L';renderDateHeader();renderEx();renderMeals();renderWater();renderHist();renderProfile();renderMonthly();progress();updateDayNutrition()}
function renderDateHeader(){const isToday=S.currentDate===localDate();$('#selectedDateLabel').textContent=isToday?'Hoje • '+formatDate(S.currentDate):formatDate(S.currentDate);$('#selectedDateInput').value=S.currentDate;$('#dayEyebrow').textContent=S.dayStatus==='completed'?'DIA CONCLUÍDO':isToday?'HOJE':'REGISTRO DO DIA'}
async function selectDay(date){if(!date)return;S.currentDate=date;S.plan=makePlan();S.plan.cal=S.p.calorie_target||S.plan.cal;S.plan.prot=S.p.protein_target||S.plan.prot;S.plan.carb=S.p.carbs_target||S.plan.carb;S.plan.fat=S.p.fat_target||S.plan.fat;S.plan.water=S.p.water_target_l||S.plan.water;await loadDayData();const {data:h}=await sb.from('daily_logs').select('*').eq('user_id',session.user.id).order('log_date',{ascending:false}).limit(14);S.history=h||[];await loadEvolutionData();renderApp()}
async function changeDay(delta){await selectDay(dateAdd(S.currentDate,delta))}

function renderEx(){$('#exerciseList').innerHTML=S.plan.exercises.map(e=>`<article class="item ${S.ex.has(e.key)?'done':''}"><div><span>EXERCÍCIO • ${formatDate(S.currentDate)}</span><h3>${e.name}</h3><p>${e.scheme} • descanso sugerido 90s</p></div><div class="loadBox"><input id="load_${e.key}" type="number" step="0.5" placeholder="kg"><button class="soft" onclick="saveLoad('${e.key}')">SALVAR CARGA</button><button class="check" onclick="togEx('${e.key}')">${S.ex.has(e.key)?'✓':'○'}</button></div></article>`).join('')}
async function togEx(key){S.ex.has(key)?S.ex.delete(key):S.ex.add(key);const e=S.plan.exercises.find(x=>x.key===key);await sb.from('exercise_logs').upsert({user_id:session.user.id,log_date:S.currentDate,exercise_key:key,exercise_name:e.name,completed:S.ex.has(key)},{onConflict:'user_id,log_date,exercise_key'});await persistDaily();renderEx();progress()}
function normalizeFoodItems(items){return (items||[]).map(x=>{if(typeof x==='object')return {qty:+x.qty||1,name:x.name,kcal:+x.kcal||0,p:+(x.p??x.protein_g)||0,c:+(x.c??x.carbs_g)||0,f:+(x.f??x.fat_g)||0,portion:x.portion||x.portion_label||''};const txt=String(x).replace(/^\d+×\s*/,''),lib=S.foods.find(f=>f.name.toLowerCase()===txt.toLowerCase());return lib?{qty:1,name:lib.name,kcal:+lib.kcal,p:+lib.p,c:+lib.c,f:+lib.f,portion:lib.portion}:{qty:1,name:txt,kcal:0,p:0,c:0,f:0,portion:''}})}
function foodLabel(x){return `${x.qty>1?x.qty+'× ':''}${x.name}`}
function enrichMeal(m){if(!m.foodItems)m.foodItems=normalizeFoodItems(m.foods);const t=mealTotals(m);if(t.kcal>0){m.target=Math.round(t.kcal);m.protein=t.p;m.carbs=t.c;m.fat=t.f}m.foods=m.foodItems.map(foodLabel);return m}
function mealTotals(m){return (m.foodItems||[]).reduce((a,x)=>({kcal:a.kcal+(+x.kcal||0)*(+x.qty||1),p:a.p+(+x.p||0)*(+x.qty||1),c:a.c+(+x.c||0)*(+x.qty||1),f:a.f+(+x.f||0)*(+x.qty||1)}),{kcal:0,p:0,c:0,f:0})}
function dayNutrition(){return S.plan.meals.map(enrichMeal).reduce((a,m)=>{const t=mealTotals(m);a.kcal+=t.kcal;a.p+=t.p;a.c+=t.c;a.f+=t.f;return a},{kcal:0,p:0,c:0,f:0})}
function updateDayNutrition(){const t=dayNutrition();$('#cal').textContent=`${Math.round(t.kcal).toLocaleString('pt-BR')} / ${S.plan.cal.toLocaleString('pt-BR')} kcal`;$('#prot').textContent=`${Math.round(t.p)} / ${S.plan.prot} g`;$('#carb').textContent=`${Math.round(t.c)} / ${S.plan.carb} g`;$('#fat').textContent=`${Math.round(t.f)} / ${S.plan.fat} g`}
function renderMeals(){S.plan.meals.sort((a,b)=>(a.time||'').localeCompare(b.time||''));$('#mealList').innerHTML=S.plan.meals.map(m=>{enrichMeal(m);const t=mealTotals(m);return `<article class="item ${S.mealsDone.has(m.key)?'done':''}"><div><span>${m.time} • ${Math.round(t.kcal||m.target)} kcal • P${Math.round(t.p||0)} C${Math.round(t.c||0)} G${Math.round(t.f||0)}</span><h3>${m.name}</h3><p>${m.foods.join(' + ')||'Sem alimentos'}</p></div><div class="mealButtons"><button class="soft mini" onclick="openEditMeal('${m.key}')">EDITAR</button><button class="check" onclick="togMeal('${m.key}')">${S.mealsDone.has(m.key)?'✓':'○'}</button></div></article>`}).join('');updateDayNutrition()}
async function togMeal(key){S.mealsDone.has(key)?S.mealsDone.delete(key):S.mealsDone.add(key);const m=S.plan.meals.find(x=>x.key===key);await persistMeal(m);await persistDaily();renderMeals();progress()}
async function addWater(v){S.water=Math.max(0,S.water+v);await persistDaily();renderWater();progress();toast('Hidratação registrada ✓')}
function renderWater(){$('#waterNow').textContent=S.water.toFixed(1).replace('.',',')+' L';$('#hWater').textContent=S.water.toFixed(1).replace('.',',')+' / '+S.plan.water.toFixed(1).replace('.',',')+' L'}
function scoreFor(t,f,w,a=null){const base=a===null?55+t*.20+f*.15+w*.10:50+t*.18+f*.14+w*.08+a*.10;return Math.min(100,Math.round(base))}
function metrics(){const t=S.plan.exercises.length?S.ex.size/S.plan.exercises.length*100:0,f=S.plan.meals.length?S.mealsDone.size/S.plan.meals.length*100:0,w=Math.min(100,S.water/S.plan.water*100),hasSteps=!!(+S.p.steps_goal&&S.steps>0),a=hasSteps?Math.min(100,S.steps/+S.p.steps_goal*100):null,pct=Math.round(hasSteps?t*.35+f*.35+w*.15+a*.15:t*.4+f*.4+w*.2),score=scoreFor(t,f,w,a);return{t,f,w,a,pct,score}}
function progress(){const {t,f,w,pct,score}=metrics(),areas=(t>=99)+(f>=99)+(w>=95);$('#pct').textContent=pct;$('#ring').style.background=`conic-gradient(var(--green) 0 ${pct}%,#e4e9e5 ${pct}%)`;$('#daySub').textContent=areas+' de 3 áreas concluídas';$('#hTrain').textContent=S.ex.size+'/'+S.plan.exercises.length+' exercícios';$('#hFood').textContent=S.mealsDone.size+'/'+S.plan.meals.length+' refeições';$('#score').textContent=score;$('#scoreText').textContent=pct>75?'EVOLUÇÃO FAVORÁVEL':pct>35?'EM ANDAMENTO':'BASELINE';$('#dayStatus').textContent=S.dayStatus==='completed'?'DIA CONCLUÍDO':'DIA EM ANDAMENTO';$('#saveDay').textContent=S.dayStatus==='completed'?'CONCLUIR NOVAMENTE / ATUALIZAR DIA ✓':'CONCLUIR MEU DIA ✓'}
async function persistDaily(status=S.dayStatus==='completed'?'completed':'in_progress'){const {t,f,w,a,score}=metrics();const {error}=await sb.from('daily_logs').upsert({user_id:session.user.id,log_date:S.currentDate,training_pct:t,nutrition_pct:f,hydration_pct:w,activity_pct:a,water_l:S.water,score,status},{onConflict:'user_id,log_date'});if(error)throw error}
function requestFinishDay(){const m=metrics();$('#finishDayText').innerHTML=`Seu dia está em <b>${m.pct}%</b>. Você pode concluir mesmo com itens pendentes — é justamente assim que o Σ Radar aprende com a rotina real.`;$('#finishDaySummary').innerHTML=`<div><span>TREINO</span><b>${S.ex.size}/${S.plan.exercises.length}</b></div><div><span>REFEIÇÕES</span><b>${S.mealsDone.size}/${S.plan.meals.length}</b></div><div><span>HIDRATAÇÃO</span><b>${S.water.toFixed(1).replace('.',',')} / ${S.plan.water.toFixed(1).replace('.',',')} L</b></div><div><span>Σ SCORE</span><b>${m.score}</b></div>`;$('#finishDayModal').classList.add('open')}
function closeFinishDay(){$('#finishDayModal').classList.remove('open')}
async function confirmFinishDay(){try{const closingMonth=dateAdd(S.currentDate,1).slice(0,7)!==S.currentDate.slice(0,7);await persistDaily('completed');S.dayStatus='completed';closeFinishDay();toast(closingMonth?'Mês fechado. Preparando o Σ Radar Mensal…':'Dia salvo. Abrindo o próximo registro…');const next=dateAdd(S.currentDate,1);setTimeout(async()=>{await selectDay(next);if(closingMonth)go('monthly')},550)}catch(e){toast('Não consegui salvar: '+(e.message||e))}}
function renderHist(){const h=S.history;$('#history').innerHTML=h.map(d=>`<div class="hist"><b>${d.log_date}</b><span>treino ${Math.round(d.training_pct)}% • alimentação ${Math.round(d.nutrition_pct)}% • água ${Math.round(d.hydration_pct)}% • ${d.status==='completed'?'concluído':'aberto'}</span><b>${d.score}</b></div>`).join('');if(h.length){const av=k=>Math.round(h.reduce((a,x)=>a+(+x[k]||0),0)/h.length);$('#wTrain').textContent=av('training_pct')+'%';$('#wFood').textContent=av('nutrition_pct')+'%';$('#wWater').textContent=av('hydration_pct')+'%';$('#wAdh').textContent=av('score');$('#weekTitle').textContent='Seu Radar já está aprendendo.';$('#weekText').textContent='Temos '+h.length+' registro(s) recentes para comparar.';$('#keep').textContent=av('training_pct')>=75?'Consistência de treino.':'Continue registrando com precisão.';$('#inc').textContent=av('hydration_pct')<80?'Hidratação diária.':av('nutrition_pct')<80?'Aderência alimentar e proteína.':'Progressão gradual.';$('#red').textContent='Mudanças bruscas. Ajuste apenas o que os dados justificarem.'}}

function go(v){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.v===v));$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));scrollTo(0,0)}$$('.nav').forEach(b=>b.onclick=()=>go(b.dataset.v))
function toggleCoach(){$('#coachPanel').classList.toggle('open')}
function addC(t,w='coach'){const d=document.createElement('div');d.className='bubble '+w;d.innerHTML=t;$('#coachTalk').appendChild(d);$('#coachTalk').scrollTop=$('#coachTalk').scrollHeight}
async function quick(t){addC(t,'user');await replyC(t)}
async function sendCoach(){const i=$('#coachInput'),t=i.value.trim();if(!t)return;i.value='';await quick(t)}
async function replyC(message){addC('<span class="coachTyping">Σ Coach analisando seu dia…</span>');const typing=$('#coachTalk').lastElementChild;try{const {data,error}=await sb.functions.invoke('coach',{body:{message,current_date:S.currentDate,plan:{calories:S.plan.cal,protein:S.plan.prot,carbs:S.plan.carb,fat:S.plan.fat,water:S.plan.water,meals:S.plan.meals,exercises:S.plan.exercises},client_progress:{completed_exercises:[...S.ex],completed_meals:[...S.mealsDone],water_l:S.water}}});typing.remove();if(error)throw error;if(data?.message)addC(data.message);if(data?.proposal)showCoachProposal(data.proposal);else if(!data?.message)fallbackCoach(message)}catch(e){typing.remove();fallbackCoach(message)}}
function fallbackCoach(message){const s=message.toLowerCase();if(/lanche/.test(s)&&/ceia|jantar|agora/.test(s)){const missed=S.plan.meals.find(m=>/lanche/.test(m.name.toLowerCase())&&!S.mealsDone.has(m.key));const target=S.plan.meals.find(m=>/ceia|jantar/.test(m.name.toLowerCase()))||S.plan.meals.at(-1);if(missed){const extra=Math.min(250,Math.round(missed.target*.55));addC(`Entendi. Você pulou <b>${missed.name}</b> (alvo de ~${missed.target} kcal). Como está indo para <b>${target.name}</b>, eu não tentaria repor tudo de uma vez. Uma compensação leve seria acrescentar uma opção proteica de ~20–25 g de proteína e cerca de ${extra} kcal, mantendo a refeição confortável.<br><br><b>Quer que eu acrescente “Iogurte proteico + aveia” à ${target.name}?</b>`);showCoachProposal({type:'adjust_meal',title:'Compensar refeição pulada',confirm_text:`Adicionar uma compensação leve à ${target.name}.`,payload:{meal_key:target.key,add_items:['Iogurte proteico','Aveia'],extra_kcal:extra}});return}}if(/muito calor|caloria|calórico/.test(s)){const next=Math.max(S.p.sex==='feminino'?1400:1600,S.plan.cal-200);addC(`Sua meta atual é <b>${S.plan.cal} kcal</b>. Posso reduzir para <b>${next} kcal</b>, manter a proteína alta e redistribuir as ${S.plan.count} refeições.`);showCoachProposal({type:'adjust_calories',title:'Reduzir calorias',confirm_text:`Reduzir para ${next} kcal e redistribuir o plano.`,payload:{calories:next}});return}if(/hidrata|água/.test(s)){const next=Math.round((S.plan.water+.5)*10)/10;addC(`Posso ajustar sua meta para <b>${next.toFixed(1)} L</b> por dia.`);showCoachProposal({type:'adjust_water',title:'Aumentar hidratação',confirm_text:`Nova meta: ${next.toFixed(1)} L.`,payload:{water_l:next}});return}const wm=s.match(/(?:peso|kg)[^0-9]*([0-9]+[,.]?[0-9]*)|([0-9]+[,.]?[0-9]*)\s*kg/);if(wm){const val=parseFloat((wm[1]||wm[2]).replace(',','.'));addC(`Posso registrar <b>${val.toFixed(1)} kg</b> como novo peso, sem apagar o histórico.`);showCoachProposal({type:'update_weight',title:'Registrar peso',confirm_text:`Registrar ${val.toFixed(1)} kg.`,payload:{weight_kg:val}});return}addC('Entendi. Neste momento a IA avançada ainda precisa da Edge Function configurada para interpretar esse caso com todo o contexto. Eu já deixei essa integração pronta no pacote; quando ativarmos a função, passo a responder usando perfil, plano, refeições, treino e histórico do dia.')}
function showCoachProposal(p){openConfirm(p.title||'Σ Coach sugere um ajuste',p.confirm_text||'Quer aplicar esta mudança?',()=>applyCoachProposal(p))}
async function applyCoachProposal(p){if(p.type==='adjust_calories')await applyCalories(+p.payload.calories);else if(p.type==='adjust_water')await applyWaterGoal(+p.payload.water_l);else if(p.type==='update_weight')await applyWeight(+p.payload.weight_kg);else if(p.type==='adjust_meal')await applyMealAdjustment(p.payload);else if(p.type==='mark_meal_skipped'){await sb.from('coach_actions').insert({user_id:session.user.id,action_type:p.type,payload:p.payload});addC('Registrado. Vou considerar essa refeição como não realizada no fechamento do dia.')}else addC('A sugestão foi entendida, mas essa ação ainda não tem executor habilitado no site.')}
function askLowerCalories(){toggleCoach();quick('Achei meu plano muito calórico')}
function openConfirm(title,text,fn){$('#confirmTitle').textContent=title;$('#confirmText').textContent=text;$('#confirmApply').onclick=async()=>{try{await fn();closeConfirm()}catch(e){toast('Erro no ajuste: '+(e.message||e))}};$('#confirmModal').classList.add('open')}function closeConfirm(){$('#confirmModal').classList.remove('open')}
async function applyCalories(next){S.plan.cal=next;S.plan.carb=Math.max(80,Math.round((next-S.plan.prot*4-S.plan.fat*9)/4));S.plan.meals.forEach(m=>m.target=Math.round(next/S.plan.count));S.p.calorie_target=next;S.p.carbs_target=S.plan.carb;await upsertProfile({id:session.user.id,calorie_target:next,carbs_target:S.plan.carb});await sb.from('coach_actions').insert({user_id:session.user.id,action_type:'adjust_calories',payload:{to:next}});renderApp();addC(`Pronto. Ajustei para <b>${next} kcal</b>. A proteína continua em ${S.plan.prot} g.`);toast('Plano ajustado pelo Σ Coach ✓')}
async function applyWaterGoal(next){S.plan.water=next;S.p.water_target_l=next;await upsertProfile({id:session.user.id,water_target_l:next});await sb.from('coach_actions').insert({user_id:session.user.id,action_type:'adjust_water',payload:{to:next}});renderApp();addC(`Meta alterada para <b>${next.toFixed(1)} L</b>.`);toast('Meta de hidratação ajustada ✓')}
async function applyWeight(w){S.p.current_weight_kg=w;await upsertProfile({id:session.user.id,current_weight_kg:w});await sb.from('body_logs').upsert({user_id:session.user.id,log_date:S.currentDate,weight_kg:w},{onConflict:'user_id,log_date'});await sb.from('coach_actions').insert({user_id:session.user.id,action_type:'update_weight',payload:{weight:w,date:S.currentDate}});addC(`Novo peso de <b>${w.toFixed(1)} kg</b> registrado para ${formatDate(S.currentDate)}.`);toast('Novo peso registrado ✓')}
async function applyMealAdjustment(payload){const m=S.plan.meals.find(x=>x.key===payload.meal_key)||S.plan.meals.at(-1);enrichMeal(m);const ops=payload.operations||[];if(!ops.length&&payload.add_items)for(const name of payload.add_items)ops.push({op:'add',food_name:name,qty:1});for(const op of ops){if(op.op==='remove'){m.foodItems=m.foodItems.filter(x=>x.name.toLowerCase()!==String(op.food_name||'').toLowerCase())}else if(op.op==='add'||op.op==='replace'){if(op.op==='replace')m.foodItems=m.foodItems.filter(x=>x.name.toLowerCase()!==String(op.from||'').toLowerCase());const f=S.foods.find(x=>x.name.toLowerCase()===String(op.food_name||op.to||'').toLowerCase());if(!f)continue;const ex=m.foodItems.find(x=>x.name===f.name);if(ex)ex.qty+=+(op.qty||1);else m.foodItems.push({qty:+op.qty||1,name:f.name,kcal:+f.kcal,p:+f.p,c:+f.c,f:+f.f,portion:f.portion||''})}else if(op.op==='set_qty'){const x=m.foodItems.find(x=>x.name.toLowerCase()===String(op.food_name||'').toLowerCase());if(x)x.qty=Math.max(.5,+op.qty||1)}else if(op.op==='set_time'&&op.time)m.time=op.time}await persistMeal(m);await sb.from('coach_actions').insert({user_id:session.user.id,action_type:'adjust_meal',payload:{operations:ops,date:S.currentDate,meal_key:m.key}});renderMeals();const t=mealTotals(m);addC(`Ajustado. <b>${m.name}</b> ficou com ${Math.round(t.kcal)} kcal • P${Math.round(t.p)} C${Math.round(t.c)} G${Math.round(t.f)}.`);toast('Refeição recalculada pelo Sigma ✓')}

function openFood(){$('#foodModal').classList.add('open');S.selected.clear();renderFoods()}function closeFood(){$('#foodModal').classList.remove('open')}$$('.filters button').forEach(b=>b.onclick=()=>{S.filter=b.dataset.f;$$('.filters button').forEach(x=>x.classList.toggle('active',x===b));renderFoods()})
function renderFoods(){const q=($('#foodSearch').value||'').toLowerCase(),list=S.foods.map((f,i)=>({f,i})).filter(x=>(S.filter==='all'||x.f.cat===S.filter)&&x.f.name.toLowerCase().includes(q));$('#foods').innerHTML=list.map(x=>{const n=S.selected.get(x.i)||0;return `<div class="foodItem ${n?'selected':''}"><div><b>${x.f.name}</b>${x.f.origin==='Meu alimento'?'<em>MEU ALIMENTO</em>':''}<small>${x.f.portion} • ${x.f.kcal} kcal • P${x.f.p} C${x.f.c} G${x.f.f}${x.f.approx?' • aprox.':''}</small></div><div class="qty"><button onclick="foodQty(${x.i},-1)">−</button><b>${n}</b><button onclick="foodQty(${x.i},1)">+</button>${x.f._customId?`<button class="deleteFood" onclick="deleteCustomFood('${x.f._customId}')">×</button>`:''}</div></div>`}).join('')||'<p class="emptyFoods">Nenhum alimento encontrado.</p>';let k=0,p=0,c=0,f=0;for(const[i,n]of S.selected){const x=S.foods[i];k+=x.kcal*n;p+=x.p*n;c+=x.c*n;f+=x.f*n}$('#foodCount').firstChild.textContent=S.selected.size+' itens • ';$('#builderTotals').textContent=`${Math.round(k)} kcal | P${Math.round(p)} C${Math.round(c)} G${Math.round(f)}`}
function foodQty(i,d){const n=Math.max(0,(S.selected.get(i)||0)+d);n?S.selected.set(i,n):S.selected.delete(i);renderFoods()}
async function saveMeal(){const name=$('#mealName').value.trim(),time=$('#mealTime').value;if(!name||!time||!S.selected.size)return toast('Informe nome, horário e alimentos.');const items=[...S.selected].map(([i,n])=>({qty:n,...S.foods[i]}));let k=0,p=0,c=0,f=0;items.forEach(x=>{k+=x.kcal*x.qty;p+=x.p*x.qty;c+=x.c*x.qty;f+=x.f*x.qty});const key='custom_'+Date.now(),foodItems=items.map(x=>({qty:x.qty,name:x.name,kcal:+x.kcal,p:+x.p,c:+x.c,f:+x.f,portion:x.portion||''})),meal={key,name,time,target:Math.round(k),foodItems,foods:foodItems.map(foodLabel)};S.plan.meals.push(meal);await sb.from('meal_logs').upsert({user_id:session.user.id,log_date:S.currentDate,meal_key:key,meal_name:name,meal_time:time,foods:foodItems,kcal:k,protein_g:p,carbs_g:c,fat_g:f,completed:false},{onConflict:'user_id,log_date,meal_key'});closeFood();renderMeals();progress();toast('Refeição adicionada ✓')}
function openCustomFood(){$('#customFoodModal').classList.add('open')}function closeCustomFood(){$('#customFoodModal').classList.remove('open')}
async function saveCustomFood(){const name=$('#cfName').value.trim(),category=$('#cfCat').value,portion=$('#cfPortion').value.trim(),kcal=+$('#cfKcal').value,protein=+$('#cfProtein').value,carbs=+$('#cfCarb').value,fat=+$('#cfFat').value;if(!name||!portion||Number.isNaN(kcal))return toast('Preencha nome, porção e dados nutricionais.');const {error}=await sb.from('custom_foods').insert({user_id:session.user.id,name,category,portion_label:portion,kcal,protein_g:protein||0,carbs_g:carbs||0,fat_g:fat||0});if(error)return toast(error.message);closeCustomFood();await loadFoods();toast('Alimento salvo na sua biblioteca ✓')}
async function deleteCustomFood(id){if(!confirm('Excluir este alimento personalizado?'))return;const {error}=await sb.from('custom_foods').delete().eq('id',id).eq('user_id',session.user.id);if(error)return toast(error.message);await loadFoods();renderFoods();toast('Alimento excluído')}

async function persistMeal(m){enrichMeal(m);const t=mealTotals(m);await sb.from('meal_logs').upsert({user_id:session.user.id,log_date:S.currentDate,meal_key:m.key,meal_name:m.name,meal_time:m.time,foods:m.foodItems,kcal:t.kcal,protein_g:t.p,carbs_g:t.c,fat_g:t.f,completed:S.mealsDone.has(m.key)},{onConflict:'user_id,log_date,meal_key'})}
function openEditMeal(key){const m=S.plan.meals.find(x=>x.key===key);if(!m)return;enrichMeal(m);S.editingMealKey=key;$('#editMealTitle').textContent='Editar '+m.name;$('#editMealName').value=m.name;$('#editMealTime').value=m.time;renderEditMealItems();$('#editFoodSearch').value='';$('#editFoodResults').innerHTML='';$('#editMealModal').classList.add('open')}
function closeEditMeal(){$('#editMealModal').classList.remove('open');S.editingMealKey=null}
function renderEditMealItems(){const m=S.plan.meals.find(x=>x.key===S.editingMealKey);if(!m)return;$('#editMealItems').innerHTML=m.foodItems.map((x,i)=>`<div class="editMealItem"><div><b>${x.name}</b><small>${x.portion||''} • ${Math.round(x.kcal*x.qty)} kcal</small></div><div class="qty"><button onclick="editMealQty(${i},-1)">−</button><b>${x.qty}</b><button onclick="editMealQty(${i},1)">+</button><button class="deleteFood" onclick="removeMealFood(${i})">×</button></div></div>`).join('')||'<p>Nenhum alimento. Adicione um abaixo.</p>'}
function editMealQty(i,d){const m=S.plan.meals.find(x=>x.key===S.editingMealKey);m.foodItems[i].qty=Math.max(.5,(+m.foodItems[i].qty||1)+d);renderEditMealItems()}
function removeMealFood(i){const m=S.plan.meals.find(x=>x.key===S.editingMealKey);m.foodItems.splice(i,1);renderEditMealItems()}
function renderEditFoodSearch(){const q=($('#editFoodSearch').value||'').trim().toLowerCase();if(!q)return $('#editFoodResults').innerHTML='';const list=S.foods.filter(f=>f.name.toLowerCase().includes(q)).slice(0,8);$('#editFoodResults').innerHTML=list.map(f=>`<button onclick="addFoodToEditedMeal('${encodeURIComponent(f.name)}')"><b>${f.name}</b><small>${f.portion} • ${f.kcal} kcal • P${f.p} C${f.c} G${f.f}</small></button>`).join('')}
function addFoodToEditedMeal(enc){const name=decodeURIComponent(enc),f=S.foods.find(x=>x.name===name),m=S.plan.meals.find(x=>x.key===S.editingMealKey);if(!f||!m)return;const existing=m.foodItems.find(x=>x.name===f.name);if(existing)existing.qty+=1;else m.foodItems.push({qty:1,name:f.name,kcal:+f.kcal,p:+f.p,c:+f.c,f:+f.f,portion:f.portion||''});renderEditMealItems();$('#editFoodSearch').value='';$('#editFoodResults').innerHTML=''}
async function saveEditedMeal(){const m=S.plan.meals.find(x=>x.key===S.editingMealKey);if(!m)return;m.name=$('#editMealName').value.trim()||m.name;m.time=$('#editMealTime').value||m.time;await persistMeal(m);await sb.from('coach_actions').insert({user_id:session.user.id,action_type:'manual_meal_edit',payload:{date:S.currentDate,meal_key:m.key}});closeEditMeal();renderMeals();progress();toast('Refeição atualizada e totais recalculados ✓')}
async function deleteCurrentMeal(){const m=S.plan.meals.find(x=>x.key===S.editingMealKey);if(!m||!confirm('Excluir esta refeição deste dia?'))return;await sb.from('meal_logs').upsert({user_id:session.user.id,log_date:S.currentDate,meal_key:m.key,meal_name:m.name,meal_time:m.time,foods:[],kcal:0,protein_g:0,carbs_g:0,fat_g:0,completed:false,deleted:true},{onConflict:'user_id,log_date,meal_key'}).catch(()=>{});S.plan.meals=S.plan.meals.filter(x=>x.key!==m.key);closeEditMeal();renderMeals();progress();toast('Refeição excluída deste dia')}
async function saveLoad(key){const val=+$('#load_'+key).value;if(!val)return toast('Informe a carga em kg.');const e=S.plan.exercises.find(x=>x.key===key);const {error}=await sb.from('load_logs').insert({user_id:session.user.id,log_date:S.currentDate,exercise_key:key,exercise_name:e.name,load_kg:val,scheme:e.scheme});if(error)return toast(error.message);await loadEvolutionData();renderProfile();toast('Carga registrada ✓')}
async function loadEvolutionData(){if(!sb||!session)return;const [{data:b},{data:l}]=await Promise.all([sb.from('body_logs').select('*').eq('user_id',session.user.id).order('log_date',{ascending:false}).limit(60),sb.from('load_logs').select('*').eq('user_id',session.user.id).order('log_date',{ascending:false}).limit(100)]);S.bodyHistory=b||[];S.loadHistory=l||[]}
function renderProfile(){if(!$('#profileBasics'))return;const p=S.p,show=v=>v===null||v===undefined||v===''?'Não informado':v;$('#profileBasics').innerHTML=`<p><b>Objetivo</b><span>${show(p.goal_text)}</span></p><p><b>Altura</b><span>${p.height_cm?show(p.height_cm)+' cm':'Não informado'}</span></p><p><b>Peso atual</b><span>${p.current_weight_kg?Number(p.current_weight_kg).toFixed(1)+' kg':'Não informado'}</span></p><p><b>Peso-alvo</b><span>${p.target_weight_kg?Number(p.target_weight_kg).toFixed(1)+' kg':'Não informado'}</span></p><p><b>Passos/dia</b><span>${p.steps_goal?Number(p.steps_goal).toLocaleString('pt-BR'):'Não informado'}</span></p><p><b>Sono</b><span>${p.sleep_hours?p.sleep_hours+' h':'Não informado'}</span></p>`;$('#hSteps').textContent=S.steps?`${S.steps.toLocaleString('pt-BR')} / ${(p.steps_goal||'—').toLocaleString?.('pt-BR')||'—'}`:(p.steps_goal?`— / ${Number(p.steps_goal).toLocaleString('pt-BR')}`:'Não informado');$('#bodyHistory').innerHTML=S.bodyHistory.length?S.bodyHistory.slice(0,12).map(x=>`<p><b>${x.log_date}</b><span>${x.weight_kg?x.weight_kg+' kg':''}${x.waist_cm?' • '+x.waist_cm+' cm cintura':''}${x.body_fat_pct?' • '+x.body_fat_pct+'% gordura':''}${x.steps?' • '+Number(x.steps).toLocaleString('pt-BR')+' passos':''}</span></p>`).join(''):'<p>Nenhum registro ainda.</p>';$('#loadHistory').innerHTML=S.loadHistory.length?S.loadHistory.slice(0,12).map(x=>`<p><b>${x.exercise_name}</b><span>${x.load_kg} kg • ${x.log_date}</span></p>`).join(''):'<p>Nenhuma carga registrada ainda.</p>'}
function openProfileEdit(){$('#peTarget').value=S.p.target_weight_kg||'';$('#peStepsGoal').value=S.p.steps_goal||'';$('#peSleep').value=S.p.sleep_hours||'';$('#peMeds').value=S.p.medications_text||'';$('#peSupps').value=S.p.supplements_text||'';$('#profileEditModal').classList.add('open')}
function closeProfileEdit(){$('#profileEditModal').classList.remove('open')}
async function saveProfileEdit(){const obj={id:session.user.id,target_weight_kg:+$('#peTarget').value||null,steps_goal:+$('#peStepsGoal').value||null,sleep_hours:+$('#peSleep').value||null,medications_text:$('#peMeds').value.trim()||null,supplements_text:$('#peSupps').value.trim()||null};await upsertProfile(obj);S.p={...S.p,...obj};closeProfileEdit();renderProfile();toast('Perfil atualizado ✓')}
async function saveEvolution(){const w=+$('#pfWeight').value||null,waist=+$('#pfWaist').value||null,fat=+$('#pfFat').value||null,steps=+$('#pfSteps').value||null;if(!w&&!waist&&!fat&&!steps)return toast('Informe ao menos um dado.');const row={user_id:session.user.id,log_date:S.currentDate};if(w)row.weight_kg=w;if(waist)row.waist_cm=waist;if(fat)row.body_fat_pct=fat;if(steps)row.steps=steps;const {error}=await sb.from('body_logs').upsert(row,{onConflict:'user_id,log_date'});if(error)return toast(error.message);if(w){S.p.current_weight_kg=w;await upsertProfile({id:session.user.id,current_weight_kg:w})}S.steps=steps||S.steps;['pfWeight','pfWaist','pfFat','pfSteps'].forEach(id=>$('#'+id).value='');await loadEvolutionData();renderProfile();renderMonthly();progress();toast('Evolução registrada ✓')}
function renderMonthly(){if(!$('#monthMetrics'))return;const [y,m]=S.currentDate.split('-').map(Number),label=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(y,m-1,1));$('#monthLabel').textContent=label.toUpperCase();const days=S.history.filter(x=>x.log_date?.startsWith(`${y}-${String(m).padStart(2,'0')}`)&&x.status==='completed'),b=S.bodyHistory.filter(x=>x.log_date?.startsWith(`${y}-${String(m).padStart(2,'0')}`)).slice().reverse(),loads=S.loadHistory.filter(x=>x.log_date?.startsWith(`${y}-${String(m).padStart(2,'0')}`));const avg=(arr,k)=>arr.length?Math.round(arr.reduce((a,x)=>a+(+x[k]||0),0)/arr.length):null,firstW=b.find(x=>x.weight_kg)?.weight_kg,lastW=[...b].reverse().find(x=>x.weight_kg)?.weight_kg,delta=firstW&&lastW?(lastW-firstW):null;$('#monthMetrics').innerHTML=`<article><span>DIAS CONCLUÍDOS</span><b>${days.length}</b></article><article><span>ADERÊNCIA MÉDIA</span><b>${avg(days,'adherence_pct')??'—'}${days.length?'%':''}</b></article><article><span>PESO NO MÊS</span><b>${delta===null?'—':(delta>0?'+':'')+delta.toFixed(1)+' kg'}</b></article><article><span>CARGAS REGISTRADAS</span><b>${loads.length}</b></article>`;$('#monthTitle').textContent=days.length>=5?'Seu mês já tem uma história.':'Ainda estamos construindo o mês.';$('#monthEvolution').textContent=delta===null?'Sem comparação de peso suficiente — isso não prejudica as demais análises.':`Variação de peso registrada: ${delta>0?'+':''}${delta.toFixed(1)} kg.`;$('#monthHighlight').textContent=days.length?`Você concluiu ${days.length} dia(s) com aderência média de ${avg(days,'adherence_pct')}%.`:'Conclua os dias que puder; o Sigma trabalha apenas com registros reais.';$('#monthNext').textContent='O próximo plano deve considerar tendência de peso, medidas, passos, aderência e cargas disponíveis — sem tratar campos ausentes como zero.'}

async function logout(){if(sb)await sb.auth.signOut();session=null;show('landing')}function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}

(async()=>{initSupabase();S.currentDate=localDate();await loadFoods();if(sb){const {data}=await sb.auth.getSession();if(data.session){session=data.session;await loadProfileAndEnter(data.session.user)}}})();
